### ISSUE TITLE
Simulator exits before app is launched

### ISSUE THREAD

**Issue by raisen** [guilhermechapiewski/titanium-jasmine#1]
I am trying to use your framework, but the iPhone simulator is exiting before the app tries to start. I am getting the following feedback:

<pre>
[INFO] Launching application in Simulator
Unknown or unsupported SDK version: 4.2
[DEBUG] Simulator SDK Roots:
[DEBUG] 'Simulator - iPhone OS 3.2' (3.2)
        /Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator3.2.sdk
[DEBUG] 'Simulator - iPhone OS 4.0' (4.0)
        /Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator4.0.sdk
[INFO] Launched application in Simulator (2.59 seconds)
[INFO] Application has exited from Simulator
</pre>

**Comment by guilhermechapiewski** [comment]
By the error message ("Unknown or unsupported SDK version: 4.2"), it seems you don't have iOS SDK 4.2 installed. Here's what you have to do:

1) Update to last SDK version (4.3) (available at http://developer.apple.com/ios).
2) Change the "IPHONE_SDK_VERSION" variable in "bin/titanium.sh" script from "4.2" to "4.3".
3) Everything should work now.

Please let me know if this works for you.
